version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test